### ISSUE TITLE
Border does not go around all the posts.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#1]
Hey Ron

I noticed this:
![screen shot 2019-01-03 at 18 56 49](https://user-images.githubusercontent.com/5323259/50653557-332cfa80-0f8a-11e9-8c1b-6722647af842.png)

It would be good for the boundry box to be around all the posts.

**Comment by ronalfy** [comment]
I'm not seeing this in chrome. I'll defer that it's a Gutenberg bug.
