### ISSUE TITLE
Resets Terms to All

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#10]
I have noticed a few times that the Terms drop down have many times autoreset itself to All terms even though I have selected a specific term. I have had to multiple times select the various correct terms on the below page. It uses term 2019, 2018, 2017 and 2015. But resets very often when I go to edit the page back to All Terms.

Used on this dev site: http://fragmentsofawalk.com/oversikt-over-reiser/

**Comment by ronalfy** [comment]
@paaljoachim is this still a bug or did I fix it?

**Comment by paaljoachim** [comment]
It got fixed. Thanks Ron! It is much appreciated!
