### ISSUE TITLE
Not able to show 5 columns

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#12]
Hey Ron

The customer wants to show all 5 travels they plan to have so that people do not need to scroll to find the ones not seen above the fold. So I selected 5 Columns, but only 2 columns are seen.

![screen shot 2019-01-20 at 21 20 39](https://user-images.githubusercontent.com/5323259/51444576-7d87d880-1cf9-11e9-9b46-b2e0d23f994b.png)

**Comment by ronalfy** [comment]
@paaljoachim is this still the case on the front-end?

**Comment by paaljoachim** [comment]
Hey Ron. I just tested and this is now working correctly.

Thanks!
