### ISSUE TITLE
Resets: After having selected a specific term

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#13]
Hey Ron

I have noticed that when I use the custom post and select a specific category to show that after save and going back to the page that under Term it will once again say All and not the specific category term I had selected.

Steps:
1. Add Custom Posts.
Select a custom post type. A category. Select a term.
2. Save and preview. It should show correctly.
3. Go back to edit. Clicking the custom post block the terms drop down now says All. Even though it earlier said a specific Term is reset to All.

I added a mini gif to show what it looks like.

![custom-posts](https://user-images.githubusercontent.com/5323259/53475067-454d8580-3a6f-11e9-933a-f0553cfc2b85.gif)

**Comment by ronalfy** [comment]
This should be fixed now.

**Comment by paaljoachim** [comment]
That is awesome Ron!
Thank you very very much!
