### ISSUE TITLE
Limit post preview by amount of words

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#14]
Hey Ron

It would be good to be able to limit post preview by amount of words in addition to using the excerpt. As it seems the excerpt uses automatically a certain amount of words and that amount I am not able to control. If I add my own excerpt into the sidebar then I can likely control it, but I do not usually manually add an excerpt.

Here is what it looks like in the backend Gutenberg area. I am using a column block with two columns in it. To show a category on the left and another on the right.
<img width="795" alt="Screen Shot 2019-04-22 at 13 24 45" src="https://user-images.githubusercontent.com/5323259/56498522-53190780-6502-11e9-8451-e1ddece2fc52.png">

Frontend view:
<img width="1019" alt="Screen Shot 2019-04-22 at 13 24 54" src="https://user-images.githubusercontent.com/5323259/56498545-75128a00-6502-11e9-8386-3cbc83866e5b.png">

**Comment by ronalfy** [comment]
In the most recent release, I added a word count that is honored on the front-end.

**Comment by paaljoachim** [comment]
That is great Ron! One problem it also shows the first image of the post in the backend along with the featured image. I will create a new issue to show you want I mean.
