### ISSUE TITLE
Backend preview shows featured image.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#15]
Hey Ron

I went to check out the new features and noticed this in the backend:
<img width="450" alt="Screen Shot 2019-05-26 at 15 53 13" src="https://user-images.githubusercontent.com/5323259/58382755-6bcb8000-7fce-11e9-9a2b-8a0ada5b45ea.png">

It looks like the backend preview is showing the featured image. Backend should not show the featured image.

Frontend looks fine:
<img width="700" alt="Screen Shot 2019-05-26 at 15 54 12" src="https://user-images.githubusercontent.com/5323259/58382761-8867b800-7fce-11e9-8a28-58d1d8aefdcc.png">

**Comment by ronalfy** [comment]
Hmm, I can't seem to duplicate this. What theme are you using?

**Comment by ronalfy** [comment]
See if 2.1.1 fixes this.

**Comment by paaljoachim** [comment]
I switched to Twenty Nineteen theme and turned off all plugins except Gutenberg and Post Type Archive Mapping and it shows the same backend.

**Comment by paaljoachim** [comment]
I will just close this issue and if I happen to notice it again. I can always reopen.
