### ISSUE TITLE
How to add two different categories side by side?

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#18]
Hey Ron

I am looking into creating a site that has two columns.
Left column contains news/nyheter and right column contains events/arrangementer.
Something similar to this:

<img width="745" alt="Screen Shot 2019-08-21 at 18 23 33" src="https://user-images.githubusercontent.com/5323259/63543225-9d4add80-c522-11e9-98cb-08908be420f6.png">

The goal to create a site that shows various category posts mixed in between in each other. Creating a flow of various posts. Btw here is a Norwegian site: https://debatt1.no/ It shows a mix of various categories.

![Screen Shot 2019-08-22 at 21 22 34](https://user-images.githubusercontent.com/5323259/63543401-06325580-c523-11e9-9034-949ba77c58e9.png)

**Comment by ronalfy** [comment]
Planning on this being a separate block.

**Comment by ronalfy** [comment]
@paaljoachim closing this now as the Featured Post by Category block is due for release.

The block is designed to be in columns or standalone for a wide layout.
