### ISSUE TITLE
Adding Category and Tags

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#2]
Hey Ron

Here is a suggestion:

![categories-tags](https://user-images.githubusercontent.com/5323259/50653889-5a37fc00-0f8b-11e9-8314-f09ac9dc413f.jpg)

NB! Hmm we might need single and plural here such as category and categories word options.
(As one switches the words for other languages single and plural options might be needed.)

Layout suggestion

From:
![screen shot 2019-01-03 at 19 13 35](https://user-images.githubusercontent.com/5323259/50654286-a0da2600-0f8c-11e9-9d31-99e33a1910f7.png)

To:

![categories-tags-layout](https://user-images.githubusercontent.com/5323259/50654103-0e398700-0f8c-11e9-88c7-8eae66646145.jpg)

Btw
it would be good with an option to turn of all capitalization of the letters.

**Comment by ronalfy** [comment]
Due to the limitations of React, I could not dynamically allow for the changing or displaying of individual taxonomies. I do show them by default, and there is a way to turn taxonomies off.
