### ISSUE TITLE
No featured image added.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#22]
Hey Ron

Some posts do not have a featured image. That means it looks like this in the backend:
![Screen Shot 2019-09-09 at 07 45 50](https://user-images.githubusercontent.com/5323259/64505921-f615c680-d2d5-11e9-8ecd-fa415e4accf6.png)

I am thinking that when there are no featured image included in a post then there could just be an invisible space where the image was supposed to be so that it looks similar in the backend to the other posts that do have a featured image.

**Comment by ronalfy** [comment]
@paaljoachim I added an option for a default fallback image. Hopefully that should help with this issue.

**Comment by paaljoachim** [comment]
Thanks Ron!
