### ISSUE TITLE
Feature request: archive mapping for taxonomies

### ISSUE THREAD

**Issue by voneff** [ronalfy/post-type-archive-mapping#24]
Hi @ronalfy 

The post type archive mapping feature is pure gold.

One suggestion: How about extending that functionality to (custom) taxonomy archives as well?
As far as I understand it I can only set a custom archive for post types to the a static page. in "Settings > Reading".

It would be really helpful if I could build additional archives for the taxonomies in the same way – especially as they are linked to from the archive block.

Cheers
Alex

**Comment by ronalfy** [comment]
@voneff I've tried setting a page for a "taxonomy" archive and it always 404's. I don't think there's a way currently to map a taxonomy to a page, but I can do so with Taxonomy terms.

**Comment by ronalfy** [comment]
Adding terms would be complicated as well as there can be so many! I'm not sure this one is feasible given my time constraints.
