### ISSUE TITLE
A similar featured post widget from before Gutenberg.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#3]
Hey Ron

On my tutorial site: https://easywebdesigntutorials.com
I use a custom Genesis - StudioPress child theme. In it I use the Featured Post widget.

(I just want to share how Genesis did this before Gutenberg.)

<img width="572" alt="screen shot 2019-01-03 at 21 28 37" src="https://user-images.githubusercontent.com/5323259/50660087-dc7deb80-0f9e-11e9-82b9-341be4db567d.png">

Notice the following options:
Image Size.
Image alignment

This is how I use it on the front page:

<img width="1197" alt="screen shot 2019-01-03 at 21 31 53" src="https://user-images.githubusercontent.com/5323259/50660149-18b14c00-0f9f-11e9-9958-f8d0100a0f84.png">

<img width="1196" alt="screen shot 2019-01-03 at 21 32 10" src="https://user-images.githubusercontent.com/5323259/50660150-18b14c00-0f9f-11e9-97e0-42e48af06f9b.png">

**Comment by ronalfy** [comment]
In 2.0.0 I added a way to use a Gravatar instead of the featured image. I also added image sizes to the block. 2.0.0 should be way more flexible than the Genesis solution if used correctly.
