### ISSUE TITLE
Term Grid frontend error code

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#37]
Hey Ron

I am testing out Term Grid block. Which looks great btw.

Using Chrome.
Twenty Twenty.
Gutenberg plugin version 7.8.1
WordPress 5.4
Local site in Desktop Server.

On the frontend I am getting this error:

Warning: Illegal string offset ‘id’ in /Users/paaljoachimromdahl/Sites/test-april-2020.dev.cc/wp-content/plugins/post-type-archive-mapping-category-grid/includes/blocks/term-grid/class-terms.php on line 72
--

1 | 0.0029 | 565624 | {main}( ) | …/index.php:0
2 | 0.0030 | 568048 | require( ‘/Users/paaljoachimromdahl/Sites/test-april-2020.dev.cc/wp-blog-header.php’ ) | …/index.php:17
3 | 0.1843 | 26865880 | require_once( ‘/Users/paaljoachimromdahl/Sites/test-april-2020.dev.cc/wp-includes/template-loader.php’ ) | …/wp-blog-header.php:19
4 | 0.1860 | 26970344 | include( ‘/Users/paaljoachimromdahl/Sites/test-april-2020.dev.cc/wp-content/themes/twentytwenty/singular.php’ ) | …/template-loader.php:106
5 | 0.2191 | 27319192 | get_template_part( ) | …/singular.php:24
6 | 0.2191 | 27319760 | locate_template( ) | …/general-template.php:168
7 | 0.2191 | 27319920 | load_template( ) | …/template.php:672
8 | 0.2193 | 27330168 | require( ‘/Users/paaljoachimromdahl/Sites/test-april-2020.dev.cc/wp-content/themes/twentytwenty/template-parts/content.php’ ) | …/template.php:725
9 | 0.2215 | 27265600 | the_content( ) | …/content.php:36
10 | 0.2215 | 27265624 | apply_filters( ) | …/post-template.php:253
11 | 0.2215 | 27266024 | WP_Hook->apply_filters( ) | …/plugin.php:206
12 | 0.2216 | 27267736 | do_blocks( ) | …/class-wp-hook.php:287
13 | 0.2517 | 27364080 | render_block( ) | …/blocks.php:537
14 | 0.2517 | 27364080 | WP_Block_Type->render( ) | …/blocks.php:487
15 | 0.2518 | 27366696 | PTAM\Includes\Blocks\Term_Grid\Terms->term_grid( ) | …/class-wp-block-type.php:109

**Comment by ronalfy** [comment]
This seems to occur when you select the term grid without any options and view on the front-end. Should be fixed now.

**Comment by paaljoachim** [comment]
Yeah. It looks better now.
