### ISSUE TITLE
Term Grid alignment options?

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#38]
Upon adding a Term Grid block is shows up by default in full width.

Like so.
![Screen Shot 2020-04-12 at 16 40 01](https://user-images.githubusercontent.com/5323259/79071682-50985a80-7cdd-11ea-814b-9e3465ee8cbf.png)

I somewhat expected to have more control over the layout. By changing the width of the block similar to other Gutenberg blocks.

**Comment by ronalfy** [comment]
Added the alignment in https://github.com/ronalfy/post-type-archive-mapping/commit/d7bbef626322a728ab63334560e73ee54ddde566

Still need to work on front-end.

**Comment by ronalfy** [comment]
@paaljoachim alignment options added to backend and frontend. Dependent on theme support.
