### ISSUE TITLE
Renaming the Plugin

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/post-type-archive-mapping#39]
The plugin does:

1. Archive mapping for post type archives
2. Archive mapping for term archives
3. Has a Custom Post Types block.
4. Has a Term Grid block.
5. Will soon have a featured post by category block.

Any suggestions on renaming it? Will need a:

- [x] A new banner image
- [x] A group in Gutenberg to select the blocks.
- [x] Video tutorials for each piece of functionality

Suggestions on names:

1. Keep it the same.
2. Archive Mapping and Helper Blocks
3. Query Blocks
4. Query Blocks Unlimited

Others?

**Comment by ronalfy** [comment]
![Custom Post Types Block](https://user-images.githubusercontent.com/636521/79693155-acf40080-822e-11ea-82fb-e62bf1401eb5.png)

Potential new banner. Bought from Shutterstock. Dimensions 1544x500 according to the guidelines here: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by ronalfy** [comment]
![stock-photo-colorful-wooden-building-blocks-selective-focus-306641441-256x256](https://user-images.githubusercontent.com/636521/79693267-402d3600-822f-11ea-92b0-a682913e36a4.png)
![stock-photo-colorful-wooden-building-blocks-selective-focus-306641441-512x512](https://user-images.githubusercontent.com/636521/79693269-40c5cc80-822f-11ea-81b4-184fd999b969.png)

Proposed Icon. Shown in 512x512 and 256x256.

**Comment by ronalfy** [comment]
Icon block icon from https://www.shutterstock.com/image-photo/colorful-wooden-building-blocks-selective-focus-306641441

**Comment by ronalfy** [comment]
Just as a note, this plugin will always remain free with no add-ons or upsells. It's a community effort for this functionality/group of blocks.

**Comment by paaljoachim** [comment]
We can look at what is common between all the blocks, and from there find a name.

**Comment by ronalfy** [comment]
My friend/roomie likes: `Custom Query Blocks`.

**Comment by ronalfy** [comment]
<img width="388" alt="Screen Shot 2020-04-20 at 1 28 42 AM" src="https://user-images.githubusercontent.com/636521/79720546-6641ed00-82a6-11ea-9a9d-22282380597b.png">

This is how it looks when adding a block. All the blocks are grouped together, have block previews, and descriptions.

**Comment by paaljoachim** [comment]
The group icons look nice.
The main Custom Query Blocks icon could look like this: 
![icon-basic-set_59-cube-512](https://user-images.githubusercontent.com/5323259/79725185-23edcf80-82e9-11ea-8ad1-da94192b513c.png)

(Keeping the icons in black and white.)

**Comment by ronalfy** [comment]
As discussed, we removed the icon for now. If other block plugins begin to add theirs, it will make sense to add ours back in.

Plugin banner/icon is set. I'll work on videos in a separate issue.
