### ISSUE TITLE
Options for placement of featured image

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#4]
I am thinking there could be a drop down to give the user the option for having featured image on top, below title, below title and post meta, or bottom below post excerpt.

![post-type-archive-mapping-plugin-options-image](https://user-images.githubusercontent.com/5323259/50661120-68dddd80-0fa2-11e9-9048-fa0b329a38fc.jpg)

**Comment by ronalfy** [comment]
I added this feature in version 2.0.0.
