### ISSUE TITLE
Question: Query Builder + Layout Builder?

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/post-type-archive-mapping#41]
@paaljoachim 

So I've had this discussion with my roomie. Some of the other blocks that do Custom Post Types have a separate area for building a query, and a separate area for building a layout. Then, the block will take in the query, the layout, and display it.

However, as we discussed it, she said, "I don't want to leave the post editor."

So my question is: do we want to pursue the flexibility of a query/layout builder, or stick with specific use-case blocks?

**Comment by ronalfy** [comment]
My internal brain says there has to be a way to marry the two so that you don't have to leave the block, but it might be overly complicated as some of the blocks have become. :/

**Comment by paaljoachim** [comment]
@ronalfy let's do a zoom later on and talk about this. 
As you will need to show me some examples of what you are thinking about so we can discuss it.

**Comment by ronalfy** [comment]
The conclusion of this is:

1. Let's go into maintenance mode and perfect the existing blocks.
2. Let's wait until full-site-editing is available and reevaluate a query builder/layout builder.
3. Let's the blocks all-inclusive and not require additional third-party screens.

Thanks @paaljoachim

**Comment by ronalfy** [comment]
The conclusion of this is:

1. Let's go into maintenance mode and perfect the existing blocks.
2. Let's wait until full-site-editing is available and reevaluate a query builder/layout builder.
3. Let's the blocks all-inclusive and not require additional third-party screens.

Thanks @paaljoachim
