### ISSUE TITLE
Archive Mapping category - bug

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#45]
I happen to use Archive Mapping in a category and point it to the front page.

<img width="334" alt="Screen Shot 2020-05-01 at 15 39 55" src="https://user-images.githubusercontent.com/5323259/80809491-15919480-8bc2-11ea-8368-2455cb429bf8.png">

What happened next is I went to the front page (clicked the logo/site title) and was redirected to the category and not the main page. I went back to change the mapping to another page but the front page still was redirected to the category page.
I hard reset in Chrome and even changed browsers but the front page was still redirecting to the category page.

We had together go to phpmyAdmin select the database and in wp_postmeta search for meta key _term_mapped and then remove it.

One needs to be able to change mapping for a category or tag. So one can try out different pages. As right now it was stuck on using the front page. Even if I changed it. It did not take effect.

**Comment by ronalfy** [comment]
This should be resolved now as I have removed the term redirects.
