### ISSUE TITLE
Remove redirection of mapped pages to category pages.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#48]
I noticed the following:
An example.
Category1 is mapped to the page hello-category-1.
Linking to hello-category-1 on the frontend will automatically redirect to the Category1 archive page.

I did not select the page to be redirected to Category1 archive page. (Or understand that it would do so.)

The reason why I would map a category to a page is that I want the category page to have a similar look (like a template) to a specific page. So it could use the Custom Query Block setup from the specific page.

**Comment by ronalfy** [comment]
I have removed the redirect category and added the ability for a single page to be mapped to multiple terms.

**Comment by paaljoachim** [comment]
That sounds better!
