### ISSUE TITLE
Adding to Gutenberg column

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#5]
Hey

I am testing out the plugin and added the Custom Post blocks to a Gutenberg column area.
Turned of all the options except displaying the featured image.

![screen shot 2019-01-04 at 00 03 32](https://user-images.githubusercontent.com/5323259/50666262-35a44a00-0fb4-11e9-8b2e-d9442d90d857.png)

I noticed that the Custom Post block inside the column had very large titles. Bigger then the Post block outside of the column.

**Comment by ronalfy** [comment]
I wouldn't recommend this block be used in columns.

**Comment by paaljoachim** [comment]
Check here: https://webkonsulenten.com/

I am using it as a kind of news site would show various categories in different ways.
