### ISSUE TITLE
Change Capitilization toggle

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#51]
One thing I have noticed over a longer period of time is the Change Capitilization toggle.

When it is off all Post meta letters are capitalized.
When it is on it goes back to normal.

<img width="1008" alt="Screen Shot 2020-05-02 at 11 59 27" src="https://user-images.githubusercontent.com/5323259/80861256-a4a7b680-8c6d-11ea-828c-19c460e2d3e3.png">

How I would like to see it:
Toggle on = Capitalize all letters.
When it is off it should show regular case post meta letters.

I am thinking this might be a bit hard to do for everyone who uses the plugin today as it would be opposite of what it is at current. As I am saying that when the Toggle is on then all the letters would be capitalized.

**Comment by ronalfy** [comment]
I'm worried about breaking backwards compatibility with this.

**Comment by paaljoachim** [comment]
I'll just close it for now. 
As you say it might break backwards compatibility.
