### ISSUE TITLE
Featured Posts: Adding Columns option

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#56]
It would be nice to also add a column option to Features posts similar to the custom post block.

<img width="264" alt="Screen Shot 2020-05-02 at 14 51 51" src="https://user-images.githubusercontent.com/5323259/80864679-800b0900-8c84-11ea-9134-6005a93dbda4.png">

Featured posts similar area as it is today:
<img width="265" alt="Screen Shot 2020-05-02 at 14 54 40" src="https://user-images.githubusercontent.com/5323259/80864748-e2fca000-8c84-11ea-808c-8188ea5cbc58.png">

Add the column option to the featured posts block.

It could then look something like this on the backend and frontend with example of using 2 columns in the featured post block.

![Featured-Post-Block-2-columns](https://user-images.githubusercontent.com/5323259/80864796-3bcc3880-8c85-11ea-9ad4-cddf39602637.jpg)

The blue title line could then stretch across the top of the columns used. 

On this page: https://designkurs.com/
Scroll down to "Les også disse artiklene" or do a page search.
Then visualize the three articles seen there Julekronikk, I begynnelsen av ordet and Gode innlegg signert Andreas Wahl Blomqvist as being a part of a Featured Post Block section. Having a blue title line along the top as can be seen in the above screenshot. Then an optional line along the left, right and bottom....

**Comment by ronalfy** [comment]
@paaljoachim I'd rather avoid this for this block because it's designed to work well using WordPress Gutenberg columns. But I'll see how feasible this is when done inside WordPress columns.

**Comment by paaljoachim** [comment]
I will also close this one for now. I will start to use the Featured Posts and get used to it, and if needed open this issue again.
