### ISSUE TITLE
Styling of Posts block

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#6]
I am thinking that there could be a border and background color for some styling of the Posts block.

Perhaps even a color styling of the post titles.

**Comment by ronalfy** [comment]
Let's put that one off and see how the recent Gutenberg changes are received. Right now it has less than 10 installs, so it's not worth my time currently for these nice-to-haves. Leaving this open as it's a good idea.

**Comment by ronalfy** [comment]
Added styling in 2.1.0. Closing.
