### ISSUE TITLE
Option to move taxonomies to the bottom.

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#7]
Hey Ron

You have added some awesome changes/options to the plugin! Great work!

One more thing I thought of was to add en option to move the taxonomies to the bottom. You could just reuse the Featured Image Location drop down for the Taxonomy placement.

**Comment by ronalfy** [comment]
2.1.0 introduces functionality to move this.

**Comment by paaljoachim** [comment]
Awesome I saw this! Thanks!
