### ISSUE TITLE
No handle bars present

### ISSUE THREAD

**Issue by paaljoachim** [ronalfy/post-type-archive-mapping#9]
Hey Ron

I updated to the newest version 2.0.1. Now I am not seeing the handlebars on the left side.

![screen shot 2019-01-19 at 17 18 29](https://user-images.githubusercontent.com/5323259/51429457-7d5ede80-1c0e-11e9-8c4d-38576d75a258.png)

**Comment by ronalfy** [comment]
I couldn't figure out a way to fix this. It's a block switcher that's disabled. Probably a Gutenberg nuance. Closing.
